// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let server = Bun.serve({
  fetch: async (request, server) => {
    server.upgrade(request);
    let username = Stdlib_Option.getOr(Primitive_option.fromNullable(request.headers.get("x-user-name")), "Unknown user");
    return new Response(`Hello ` + username + `!`, {
      status: 200
    });
  }
});

let port = server.port.toString();

let hostName = server.hostname;

console.log(`Server listening on http://` + hostName + `:` + port + `!`);

let program = "Hello, World!";

export {
  program,
  server,
  port,
  hostName,
}
/* server Not a pure module */
